'use strict';
let project={schema:1,kind:'coded_documents',id:crypto.randomUUID(),documents:[],categories:[],annotations:[],history:[]},dirty=false,selection=null;
const $=id=>document.getElementById(id),uuid=()=>crypto.randomUUID(),date=()=>new Date().toISOString();
function message(text){$('status').textContent=text}
function el(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n}
async function hash(data){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(Coding.canonical(data)));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function commit(next,action){Coding.validate(next);next.history.push({at:date(),action});project=next;dirty=true;render();autosaver.save(project)}
function guard(fn){return async(...args)=>{try{await fn(...args)}catch(e){message('Nicht ausgeführt: '+e.message)}}}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function chosen(){return project.documents.find(d=>d.id===$('document').value)}
function render(){const old=$('document').value,cat=$('category').value;$('document').replaceChildren();for(const d of project.documents){const o=el('option',d.title,$('document'));o.value=d.id}if(project.documents.some(d=>d.id===old))$('document').value=old;$('category').replaceChildren();for(const c of project.categories){const o=el('option',c.code,$('category'));o.value=c.id}if(project.categories.some(c=>c.id===cat))$('category').value=cat;renderDocument()}
function renderDocument(){selection=null;$('selection').textContent='Noch keine Textstelle markiert.';$('segments').replaceChildren();const d=chosen();if(!d)return;for(const s of d.segments){const card=el('article',undefined,$('segments'));el('h3',`Segment ${s.id} · ${s.start===null?'Zeit unbekannt':s.start.toFixed(2)+'–'+s.end.toFixed(2)+' s'}`,card);if(s.source_person_suggestion&&!s.source_person_confirmed)el('p','Quellenvorschlag für die Person: '+s.source_person_suggestion+'. Nach Textänderung erneut prüfen und Personenkennung ausdrücklich eintragen.',card);const lab=el('label','Personenkennung ',card),person=el('input',undefined,lab);person.value=s.person;person.oninput=guard(()=>{project.documents.find(x=>x.id===d.id).segments.find(x=>x.id===s.id).person=person.value.trim();dirty=true;autosaver.save(project)});const exLabel=el('label','Vom Analyseexport ausschließen (z. B. Interviewfrage) ',card),ex=el('input',undefined,exLabel);ex.type='checkbox';ex.checked=s.exclude;ex.onchange=()=>{const next=structuredClone(project);next.documents.find(x=>x.id===d.id).segments.find(x=>x.id===s.id).exclude=ex.checked;commit(next,'Exportauswahl geändert')};
const whole=el('button','Ganzes Segment auswählen',card);whole.onclick=()=>{selection={document_id:d.id,segment_id:s.id,start:0,end:Array.from(s.text).length,quote:s.text};$('selection').textContent=s.text};const text=el('div',s.text,card);text.className='text';text.onmouseup=()=>{const sel=window.getSelection();if(!sel.rangeCount||sel.isCollapsed)return;const range=sel.getRangeAt(0);if(!text.contains(range.startContainer)||!text.contains(range.endContainer)){message('Bitte innerhalb eines Segments markieren.');return}const prefix=range.cloneRange();prefix.selectNodeContents(text);prefix.setEnd(range.startContainer,range.startOffset);const start=Array.from(prefix.toString()).length,end=start+Array.from(range.toString()).length;selection={document_id:d.id,segment_id:s.id,start,end,quote:Coding.slice(s.text,start,end)};$('selection').textContent=selection.quote;for(const n of document.querySelectorAll('.selected'))n.classList.remove('selected');text.classList.add('selected')};
for(const a of project.annotations.filter(x=>x.document_id===d.id&&x.segment_id===s.id)){const line=el('div',undefined,card);line.className='annotation';el('strong',project.categories.find(c=>c.id===a.category_id).code,line);el('p',a.quote,line);el('small',(a.origin==='manual'?'Manuell':'LLM-Vorschlag, geprüft')+(a.memo?' · '+a.memo:''),line);const change=el('button','Kategorie auf aktuelle Auswahl ändern',line);change.onclick=guard(()=>{const next=structuredClone(project);next.annotations.find(x=>x.id===a.id).category_id=$('category').value;next.annotations.find(x=>x.id===a.id).origin='manual';commit(next,'Codierung manuell geändert')});const remove=el('button','Codierung entfernen',line);remove.onclick=()=>{const next=structuredClone(project);next.annotations=next.annotations.filter(x=>x.id!==a.id);commit(next,'Codierung entfernt')}}}}
$('document').onchange=renderDocument;
$('addDoc').onclick=guard(async()=>{const file=$('transcriptFile').files[0];if(!file)throw Error('Bestätigtes Transkript auswählen.');const t=JSON.parse(await file.text());if(t.review?.confirmed!==true||!Array.isArray(t.segments))throw Error('Transkript zuerst mit llm_review.py bestätigen.');const segs=t.segments.map(s=>({id:String(s.id),start:s.start,end:s.end,text:s.text,speaker:s.speaker??null}));if(await hash(segs)!==t.review.segments_sha256)throw Error('Transkript nach Bestätigung verändert.');const next=structuredClone(project);next.documents.push({id:uuid(),title:$('title').value.trim()||file.name,transcript_sha256:await hash(t),transcript_confirmed:true,segments:segs.map(s=>({...s,person:'',exclude:false}))});commit(next,'Bestätigtes Dokument hinzugefügt');$('document').value=next.documents.at(-1).id;renderDocument()});
$('projectFile').onchange=guard(async e=>{if(dirty&&!confirm('Ungespeicherte Änderungen verwerfen und anderes Projekt öffnen?'))return;const next=JSON.parse(await e.target.files[0].text());Coding.validate(next);project=next;dirty=true;render();autosaver.save(project)});
$('save').onclick=guard(()=>{Coding.validate(project);download('Codierprojekt_'+new Date().toISOString().replaceAll(':','-')+'.json',JSON.stringify(project,null,2),'application/json');dirty=false;message('Projektdownload ausgelöst. Bitte im gewählten Ordner prüfen; dort sind Texte, Kategorien und Codierungen zusammen gespeichert.')});
$('setAllPerson').onclick=guard(()=>{const person=$('allPerson').value.trim(),d=chosen();if(!person||!d)throw Error('Dokument und Person angeben.');if(!confirm('Alle Segmente dieses Dokuments der Person '+person+' zuordnen? Bei Gruppeninterviews einzeln zuordnen.'))return;const next=structuredClone(project);next.documents.find(x=>x.id===d.id).segments.forEach(s=>s.person=person);commit(next,'Person für ganzes Dokument gesetzt')});
$('categoryForm').onsubmit=guard(e=>{e.preventDefault();const next=structuredClone(project),id=$('categoryId').value||uuid(),old=next.categories.find(c=>c.id===id),value={id,code:Coding.codePath($('code').value),definition:$('definition').value.trim(),inclusion:$('inclusion').value.trim(),exclusion:$('exclusion').value.trim(),anchors:old?.anchors||''};if(old)Object.assign(old,value);else next.categories.push(value);next.ui_draft={...(next.ui_draft||{}),code:'',definition:'',inclusion:'',exclusion:'',categoryId:''};commit(next,'Kategorie gespeichert');$('categoryId').value='';$('categoryForm').reset()});
$('newCategory').onclick=()=>{$('categoryForm').reset();$('categoryId').value=''};
$('editCategory').onclick=guard(()=>{const c=project.categories.find(x=>x.id===$('category').value);if(!c)throw Error('Kategorie auswählen.');$('categoryId').value=c.id;for(const k of ['code','definition','inclusion','exclusion'])$(k).value=c[k]});
$('deleteCategory').onclick=guard(()=>{const id=$('category').value;if(project.annotations.some(a=>a.category_id===id))throw Error('Kategorie wird verwendet. Erst Codierungen umordnen oder entfernen.');const next=structuredClone(project);next.categories=next.categories.filter(c=>c.id!==id);commit(next,'Kategorie entfernt')});
$('bookFile').onchange=guard(async e=>{const book=JSON.parse(await e.target.files[0].text());if(book.kind!=='approved_categories'||book.review?.confirmed!==true||await hash(book.categories)!==book.review.categories_sha256)throw Error('Bestätigtes, unverändertes Kategoriensystem benötigt.');const next=structuredClone(project);for(const c of book.categories){const value={id:c.id,code:Coding.codePath(c.code),definition:c.definition,inclusion:c.inclusion,exclusion:c.exclusion,anchors:c.evidence.map(x=>x.quote).join('\n')};const existing=next.categories.find(x=>x.id===c.id);if(existing){if(Coding.canonical(existing)!==Coding.canonical(value))throw Error('Kategorie-ID existiert bereits mit anderem Inhalt.');}else next.categories.push(value)}commit(next,'Geprüftes Kategoriensystem importiert')});
$('assign').onclick=guard(()=>{if(!selection)throw Error('Textstelle markieren.');const a={...selection,id:uuid(),category_id:$('category').value,origin:'manual',memo:$('memo').value};commit(Coding.addAnnotation(project,a),'Textstelle manuell codiert')});
$('codingFile').onchange=guard(async e=>{const d=chosen();if(!d)throw Error('Dokument auswählen.');const value=JSON.parse(await e.target.files[0].text());if(value.review?.coding_sha256!==await hash(value.coding))throw Error('Bestätigte Codierungen wurden verändert.');const additions=Coding.suggestionsFor(project,d.id,value);let next=structuredClone(project);for(const a of additions)next=Coding.addAnnotation(next,{...a,id:uuid()});commit(next,'Geprüfte LLM-Codierungen importiert')});
$('export').onclick=guard(()=>{const out=Coding.exportsFor(project);download('Kategoriesystem.csv',out.categories,'text/csv;charset=utf-8');download('maxqda_export.csv',out.segments,'text/csv;charset=utf-8');message(out.count+' Codierzeilen exportiert. Ggf. beide Downloads im Browser erlauben. Gleiche Textstelle behält bei Mehrfachcodierung dieselbe PassageID; jede Codierzeile hat eine eigene segment_id.')});
$('report').onclick=guard(()=>{Coding.validate(project);const page=document.implementation.createHTMLDocument('Codierte Dokumente');page.documentElement.lang='de';const meta=page.createElement('meta');meta.charset='utf-8';page.head.prepend(meta);const style=page.createElement('style');style.textContent='body{font:17px system-ui;max-width:1000px;margin:30px auto;padding:20px}p{white-space:pre-wrap}aside{border-left:4px solid #46856a;padding:12px;background:#f3f7f4}';page.head.append(style);el('h1','Codierte Dokumente',page.body);el('p','Gespeichert: '+date()+'. Segmentzeiten sind keine genauen Grenzen ausgewählter Teilzitate.',page.body);for(const d of project.documents){el('h2',d.title,page.body);for(const s of d.segments){el('h3',`Segment ${s.id} · ${s.start}–${s.end} s · ${s.person||'Person offen'}${s.exclude?' · vom Export ausgeschlossen':''}`,page.body);el('p',s.text,page.body);for(const a of project.annotations.filter(x=>x.document_id===d.id&&x.segment_id===s.id)){const box=el('aside',undefined,page.body);el('strong',project.categories.find(c=>c.id===a.category_id).code,box);el('p',a.quote,box);el('small',a.origin+' '+a.memo,box)}}}download('Codierte_Dokumente.html','<!doctype html>'+page.documentElement.outerHTML,'text/html;charset=utf-8')});
const autosaver=new ProjectAutosave(window.WORKSPACE_CONFIG,message);
window.addEventListener('project-saved',()=>{dirty=false});
for(const key of ['code','definition','inclusion','exclusion','memo','title','allPerson'])$(key).addEventListener('input',()=>{project.ui_draft=Object.fromEntries(['code','definition','inclusion','exclusion','memo','title','allPerson','categoryId'].map(k=>[k,$(k).value]));dirty=true;autosaver.save(project)});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
(async()=>{const controls=[...document.querySelectorAll('input,textarea,button,select')].map(n=>[n,n.disabled]);for(const [n]of controls)n.disabled=true;try{const saved=await autosaver.load();for(const [n,disabled]of controls)n.disabled=disabled;if(saved){Coding.validate(saved);project=saved;}render();if(project.import_draft){preview=project.import_draft;el('p','Importentwurf wiederhergestellt. Prüfe die gespeicherten Abschnitte vor der Bestätigung.',$('preview'));for(const s of preview.segments){const label=el('label','Abschnitt '+s.id,$('preview'));const area=el('textarea',s.text,label);area.oninput=()=>{s.text=area.value;project.import_draft=preview;autosaver.save(project)}}$('confirmImport').disabled=false;}for(const [k,v]of Object.entries(project.ui_draft||{}))if($(k))$(k).value=v;}catch(e){message('Projekt konnte nicht geladen werden: '+e.message);}})();

$('recoverBackup').onclick=()=>{const backup=window.unresolvedCodingBackup;if(!backup){message('Kein konfliktbehafteter Browser-Zwischenstand vorhanden.');return}download('Browser_Rettung.json',JSON.stringify(backup.project,null,2),'application/json')};
let preview=null;
$('previewImport').onclick=guard(async()=>{if(!window.WORKSPACE_CONFIG)throw Error('Import über die lokale Arbeitsansicht öffnen.');const file=$('exchangeFile').files[0];if(!file)throw Error('Transkriptdatei wählen.');if(file.size>20*1024*1024)throw Error('Importlimit 20 MiB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const r=await fetch('/import',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':window.WORKSPACE_CONFIG.token},body:JSON.stringify({filename:file.name,data:btoa(binary),encoding:$('encoding').value||null})});preview=await r.json();if(!r.ok)throw Error(preview.error);$('preview').replaceChildren();el('p',preview.warnings.join(' '),$('preview'));for(const s of preview.segments){const label=el('label',`Abschnitt ${s.id} · Sprecherhinweis: ${s.speaker||'offen'} · Zeit: ${s.start??'unbekannt'}`,$('preview'));const area=el('textarea',s.text,label);area.oninput=()=>{s.text=area.value;project.import_draft=preview;autosaver.save(project)}}project.import_draft=preview;autosaver.save(project);$('confirmImport').disabled=false;});
$('confirmImport').onclick=guard(async()=>{if(!preview)throw Error('Erst Vorschau erzeugen.');if(!$('importChecked').checked)throw Error('Vorschau zuerst prüfen und bestätigen.');const r=await fetch('/confirm-import',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':window.WORKSPACE_CONFIG.token},body:JSON.stringify({transcript:preview,reviewer:$('importReviewer').value})});const result=await r.json();if(!r.ok)throw Error(result.error);const t=result.transcript,next=structuredClone(project);next.documents.push({id:uuid(),title:preview.source_name,transcript_sha256:await hash(t),transcript_confirmed:true,segments:t.segments.map(s=>({...s,person:'',exclude:false}))});delete next.import_draft;commit(next,'Transkriptimport bestätigt');$('preview').replaceChildren();preview=null;$('confirmImport').disabled=true;$('importChecked').checked=false;});
