'use strict';const token=document.querySelector('meta[name="review-token"]').content,cards=new Map(),queue=new Map();let state={revision:0},busy=false,cacheKey='',drafts={};const $=id=>document.getElementById(id);
function el(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n}
async function post(path,value){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':token},body:JSON.stringify(value)});const v=await r.json();if(!r.ok)throw Error(v.error);return v}
function cache(){try{localStorage.setItem(cacheKey,JSON.stringify(drafts))}catch(e){$('saved').textContent='Browser-Zwischensicherung fehlgeschlagen: '+e.message}}
function enqueue(c){c.dirty=true;c.note.textContent='Speichert …';const item={segment_id:c.segment.id,source_sha256:c.segment.source_sha256,text:c.area.value};drafts[c.segment.id]=item;cache();queue.set(c.segment.id,item);flush()}
async function flush(){if(busy||!queue.size)return;busy=true;const [id,item]=queue.entries().next().value;queue.delete(id);const c=cards.get(id);try{const latest=await post('/edit',{...item,revision:state.revision});if(c.area.value===item.text){c.dirty=false;delete drafts[id];cache()}render(latest);if(!c.dirty)c.note.textContent='Automatisch auf Datenträger gespeichert.'}catch(e){c.note.textContent='NICHT gespeichert: '+e.message+' Eingabe bleibt in der Browser-Sicherung. Erneut speichern oder neu laden.';c.note.className='warning'}finally{busy=false;if(queue.size)flush()}}
function render(v){state=v;if(!cacheKey){cacheKey='qa-transcript-'+v.workspace_key;try{drafts=JSON.parse(localStorage.getItem(cacheKey)||'{}')}catch{drafts={}}}$('status').textContent=`${v.title} · ${v.status} · ${v.segments.length} Textabschnitte · ${v.saved_edits} gespeicherte Korrekturen${v.error?' · '+v.error:''}`;$('audio').hidden=!v.audio_available;$('finish').disabled=v.status!=='completed'||v.segments.some(s=>s.conflict);
for(const s of v.segments){let c=cards.get(s.id);if(!c){const card=el('article',undefined,$('segments'));const title=el('h2','',card),hear=el('button','Ab hier hören',card),original=el('details',undefined,card);el('summary','Rohtranskript anzeigen',original);const raw=el('p','',original),area=el('textarea',undefined,card),note=el('p','',card),save=el('button','Speicherung erneut versuchen',card);c={card,title,raw,area,note,save,dirty:false,segment:s};cards.set(s.id,c);area.value=s.display_text;area.oninput=()=>enqueue(c);hear.onclick=()=>{$('audio').currentTime=c.segment.start;$('audio').play().catch(e=>{$('saved').textContent=e.message})};save.onclick=()=>enqueue(c);const draft=drafts[s.id];if(draft){area.value=draft.text;c.dirty=true;if(draft.source_sha256===s.source_sha256&&draft.text!==s.display_text){queue.set(s.id,draft);setTimeout(flush,0)}else if(draft.text===s.display_text){c.dirty=false;delete drafts[s.id];cache()}else{note.textContent='Browser-Entwurf trifft auf geändertes Original. Erneut prüfen und speichern.'}}}
c.segment=s;c.title.textContent=`Segment ${s.id} · ${s.start.toFixed(2)}–${s.end.toFixed(2)} s`;c.raw.textContent=s.text;c.save.disabled=false;if(!c.dirty)c.area.value=s.display_text;if(s.conflict){c.note.className='warning';c.note.textContent='Rohtext hat sich geändert. Deine Korrektur bleibt erhalten. Gegen Original prüfen und erneut speichern.'}else if(!c.dirty)c.note.textContent=s.edited?'Korrektur auf Datenträger gespeichert.':'Rohtranskript – noch prüfen.'}
const live=new Set(v.segments.map(s=>s.id));for(const [id,c]of cards)if(!live.has(id)){c.note.textContent='Segment momentan nicht im aktuellen Rohstand. Eingabe bleibt erhalten.';c.save.disabled=true}}
async function poll(){if(!busy){try{const r=await fetch('/state',{cache:'no-store'});const v=await r.json();if(!r.ok)throw Error(v.error);render(v)}catch(e){$('status').textContent='Verbindung/Status: '+e.message}}setTimeout(poll,1000)}
$('audio').ontimeupdate=()=>{for(const c of cards.values())c.card.classList.toggle('playing',$('audio').currentTime>=c.segment.start&&$('audio').currentTime<c.segment.end)};
$('finish').onclick=async()=>{if(busy||[...cards.values()].some(c=>c.dirty)){alert('Erst automatische Speicherung aller Eingaben abwarten bzw. Speicherfehler beheben.');return}if(!confirm('Gesamtes Transkript gegen Aufnahme geprüft? Eine neue bestätigte Version wird gespeichert.'))return;busy=true;try{const r=await post('/finish',{reviewer:$('reviewer').value});$('saved').textContent='Neue Version neben dem Ergebnisordner gespeichert: '+r.filename;const blob=new Blob([JSON.stringify(r.transcript,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a','Bestätigte Version herunterladen',$('saved'));a.href=url;a.download=r.filename;}catch(e){$('saved').textContent=e.message}finally{busy=false}};
window.addEventListener('beforeunload',e=>{if([...cards.values()].some(c=>c.dirty)){e.preventDefault();e.returnValue=''}});poll();

function renderModels(v){$('autoModels').checked=v.automatic;$('modelStatus').textContent=(v.error?v.error+' ':'')+(v.checked_at?'Letzte erfolgreiche Prüfung: '+new Date(v.checked_at).toLocaleString():'Noch nicht online geprüft.')+' '+v.scope;$('modelList').replaceChildren();for(const m of v.installed||[])el('li','Installiert: '+m.name+' · Revision '+m.revision.slice(0,12),$('modelList'));for(const m of v.models){const row=el('li',undefined,$('modelList'));const link=el('a',m.repository,row);link.href=m.url;link.target='_blank';link.rel='noopener noreferrer';el('span',' · '+({current:'Stand laut Manifest aktuell',revision_available:'Andere Repository-Revision verfügbar',alternative:'Weiteres Modell verfügbar – nicht installiert'}[m.status])+(m.tested_family?'':' · im Prototyp ungeprüft'),row)}}
async function checkModels(manual){$('checkModels').disabled=true;try{renderModels(await post('/model-updates/check',{manual}))}catch(e){$('modelStatus').textContent='Modellprüfung fehlgeschlagen: '+e.message}finally{$('checkModels').disabled=false}}
$('checkModels').onclick=()=>checkModels(true);
$('autoModels').onchange=async()=>{try{const v=await post('/model-updates/preference',{automatic:$('autoModels').checked});renderModels(v);if(v.automatic)await checkModels(false)}catch(e){$('modelStatus').textContent='Einstellung nicht gespeichert: '+e.message}};
fetch('/model-updates').then(r=>{if(!r.ok)throw Error('Modellstatus nicht verfügbar.');return r.json()}).then(v=>{renderModels(v);if(v.automatic)checkModels(false)}).catch(e=>{$('modelStatus').textContent=e.message});
setInterval(()=>{if($('autoModels').checked)checkModels(false)},3600000);
