/* Pure source-range editing. The autosaved project is the authority. */
(function(root){'use strict';
function blocks(words,key){if(!words.length)return [];const out=[];let first=0,last=null,unknown=null;for(let i=0;i<words.length;i++){const current=key(words[i]);if(current===null){if(unknown===null)unknown=i;continue}if(last!==null&&current!==last){const boundary=unknown===null?i:unknown;if(boundary>first)out.push({first,last:boundary});first=boundary}last=current;unknown=null}out.push({first,last:words.length});return out}
function clip(region,first,last){const retained=region.reviewed_indices.map((n,i)=>({n,text:region.reviewed_tokens[i]})).filter(x=>first<=x.n&&x.n<last);return {...region,id:region.id.replace(/:\d+:\d+$/,'')+':'+first+':'+last,first,last,reviewed_tokens:retained.map(x=>x.text),reviewed_indices:retained.map(x=>x.n)}}
function assign(project,words,first,last,personId,exclude,id){if(!Number.isInteger(first)||!Number.isInteger(last)||first<0||last<=first)throw Error('Keine gültige Quellgrenze gewählt.');const next=structuredClone(project),regions=[];for(const old of next.speaker_overrides||[]){if(old.last<=first||old.first>=last){regions.push(old);continue}if(old.first<first)regions.push(clip(old,old.first,first));if(old.last>last)regions.push(clip(old,last,old.last))}const selected=words.filter(w=>first<=w.source_token_index&&w.source_token_index<last);if(!selected.length)throw Error('Dieser Quellbereich enthält im aktuellen Text keine Wörter. Anderen Nachbaranker wählen.');regions.push({id,first,last,person_id:personId,exclude:!!exclude,reviewed_tokens:selected.map(w=>w.text),reviewed_indices:selected.map(w=>w.source_token_index)});next.speaker_overrides=regions.sort((a,b)=>a.first-b.first);return next}
function apply(words,project){const people=new Map((project.people||[]).map(p=>[p.id,p]));return words.map(original=>{const word={...original},region=(project.speaker_overrides||[]).find(r=>r.first<=word.source_token_index&&word.source_token_index<r.last);if(!region)return word;const person=people.get(region.person_id),selected=words.filter(w=>region.first<=w.source_token_index&&w.source_token_index<region.last),stable=JSON.stringify(selected.map(w=>w.text))===JSON.stringify(region.reviewed_tokens)&&JSON.stringify(selected.map(w=>w.source_token_index))===JSON.stringify(region.reviewed_indices);return {...word,reading_person_id:region.person_id,reading_region_id:region.id,manual_assignment:true,exclude:region.exclude,speaker:region.person_id,speaker_label:person?.label||'',person:person?.name||'',person_display:person?.name||'',person_confirmed:!!person&&stable,assignment_needs_review:!!person&&!stable}})}
function selection(words,cursor,key,sourceLength,whole=false){const selected=words.findIndex(w=>w.to>cursor),index=selected<0?words.length-1:selected;if(index<0)throw Error('Kein Wortanker vorhanden.');const block=blocks(words,key).find(b=>b.first<=index&&index<b.last);const firstIndex=whole?block.first:index,nextWord=words[block.last],first=words[firstIndex].source_token_index,last=nextWord?nextWord.source_token_index:sourceLength;return {first,last,word:words[firstIndex],index:firstIndex,block}}
const api={blocks,assign,apply,selection};if(typeof module!=='undefined')module.exports=api;else root.ReadingPeople=api;
})(globalThis);
