/* Cursor offsets are UTF-16, matching textarea.selectionStart; no synthetic word times. */
(function(root){'use strict';
function localEditWords(before,after,words){if(!words.length)return [];let prefix=0;while(prefix<before.length&&prefix<after.length&&before[prefix]===after[prefix])prefix++;if(prefix&&before.charCodeAt(prefix-1)>=0xD800&&before.charCodeAt(prefix-1)<=0xDBFF)prefix--;let suffix=0;while(suffix<before.length-prefix&&suffix<after.length-prefix&&before.at(-1-suffix)===after.at(-1-suffix))suffix++;const delta=after.length-before.length,newEnd=after.length-suffix;const fallback=words.find(w=>w.to>prefix)||words.at(-1);return Array.from(after.matchAll(/\S+/gu),m=>{const from=m.index,to=from+m[0].length;let original=null;if(to<=prefix)original=words.find(w=>w.from===from&&w.to===to&&w.text===m[0]);else if(from>=newEnd)original=words.find(w=>w.from===from-delta&&w.to===to-delta&&w.text===m[0]);return original?{...original,from,to,text:m[0]}:{...fallback,from,to,text:m[0],exact:false,start:null,end:null,person_confirmed:false}})}
function atCursor(words,cursor){return words.find(w=>w.to>cursor)||words.at(-1)||null}
function confirmedPerson(word){return word.reading_person_id&&word.person_confirmed&&!word.assignment_needs_review?JSON.stringify(['confirmed-person',word.reading_person_id,!!word.exclude]):null}
function redundantBoundary(left,right){return !!(left&&right&&left.reading_region_id&&right.reading_region_id&&left.reading_region_id!==right.reading_region_id&&confirmedPerson(left)&&confirmedPerson(left)===confirmedPerson(right))}
function speakerKey(word){const confirmed=confirmedPerson(word);if(confirmed)return confirmed;if(word.reading_region_id)return 'region:'+word.reading_region_id;if(word.reading_person_id)return JSON.stringify(['person',word.reading_person_id,!!word.exclude]);return word.person?JSON.stringify(['person',word.person,word.exclude]):word.speaker?JSON.stringify(['speaker',word.speaker,word.exclude]):null}
function formatParagraphs(text,words,cursor=0,smooth=false){const gaps=words.map((w,i)=>text.slice(i?words[i-1].to:0,w.from)),keys=words.map(speakerKey);let last=null,unknownStart=null;for(let i=0;i<words.length;i++){if(redundantBoundary(words[i-1],words[i])&&/^\s+$/u.test(gaps[i])&&gaps[i].includes('\n'))gaps[i]=' ';const key=keys[i];if(key===null){if(unknownStart===null)unknownStart=i;continue}if(last!==null&&key!==last){const boundary=unknownStart===null?i:unknownStart;if(boundary>0&&!gaps[boundary].includes('\n'))gaps[boundary]='\n\n'}if(smooth&&unknownStart!==null){for(let j=unknownStart;j<=i;j++){if(j===0)continue;const boundary=last!==null&&key!==last&&j===unknownStart;if(boundary){gaps[j]='\n\n'}else if(gaps[j].includes('\n'))gaps[j]=' '}}last=key;unknownStart=null}if(smooth&&unknownStart!==null){for(let j=unknownStart;j<words.length;j++)if(j>0&&gaps[j].includes('\n'))gaps[j]=' '}
let result='',previous=0,newCursor=cursor,mapped=false;const updated=[];for(let i=0;i<words.length;i++){const word=words[i],gap=gaps[i];if(!mapped&&cursor<=word.from&&cursor>=previous){newCursor=result.length+Math.min(cursor-previous,gap.length);mapped=true}result+=gap;const from=result.length;result+=text.slice(word.from,word.to);updated.push({...word,from,to:result.length});if(!mapped&&word.from<=cursor&&cursor<=word.to){newCursor=from+cursor-word.from;mapped=true}previous=word.to}if(!mapped)newCursor=result.length+Math.max(0,cursor-previous);result+=text.slice(previous);return {text:result,words:updated,cursor:newCursor}}
function paragraphs(text,words,cursor=0){return formatParagraphs(text,words,cursor,false)}
function smoothUnknownBreaks(text,words){return formatParagraphs(text,words,0,true).text}
const api={localEditWords,atCursor,paragraphs,speakerKey,smoothUnknownBreaks,formatParagraphs};if(typeof module!=='undefined')module.exports=api;else root.Reading=api;
})(globalThis);
