/* Local model setup: explicit selection, no download or automatic fallback. */
(()=>{'use strict';const cfg=window.HOST_CONFIG;if(!cfg)return;
const base='/preparation/'+encodeURIComponent(cfg.project);
const el=(tag,text,parent)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(parent)parent.append(n);return n};
async function api(path,body={}){const response=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':cfg.token},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error||'Modellauswahl fehlgeschlagen.');return value}
const panel=el('section');panel.id='audio-model-setup';panel.setAttribute('aria-label','Lokales Transkriptionsmodell');
el('h2','Transkriptionsmodell',panel);const summary=el('p','Lokales Modell prüfen …',panel);summary.setAttribute('role','status');
const configure=el('button','Modell einrichten / ändern',panel);configure.type='button';
const processing=document.getElementById('processing');if(processing)processing.before(panel);
const dialog=el('dialog',null,document.body);dialog.id='model-setup-dialog';dialog.setAttribute('aria-label','Whisper-Modell einrichten');
el('h2','Lokales Whisper-Modell auswählen',dialog);
el('p','Whisper wird für Audio benötigt. Ollama-Modelle für die Analyse sind dafür nicht geeignet. Ein vorhandener Whisper-Modellordner enthält model_manifest.json und die zugehörigen Modelldateien.',dialog);
const knownLabel=el('label','Bereits bekannte Modellordner',dialog),known=el('select',null,knownLabel);known.id='known-audio-models';
const pathLabel=el('label','Modellordner',dialog),path=el('input',null,pathLabel);path.id='audio-model-path';path.type='text';
const browse=el('button','Ordner öffnen',dialog),up=el('button','Übergeordneter Ordner',dialog),home=el('button','Persönlicher Ordner',dialog);
const list=el('div',null,dialog);list.id='model-folders';
const rememberLabel=el('label',null,dialog),remember=el('input',null,rememberLabel);remember.type='checkbox';remember.checked=true;remember.id='remember-audio-model';rememberLabel.append('Diesen Modellordner auch für neue Projekte verwenden');
const apply=el('button','Modellordner prüfen und verwenden',dialog),cancel=el('button','Schließen',dialog);
const status=el('p',null,dialog);status.setAttribute('role','status');
const help=el('details',null,dialog);el('summary','Noch kein Whisper-Modell installiert?',help);el('p','Die Programmpakete enthalten keine großen Whisper-Modellgewichte. Ein bereits vollständig installiertes Modell mit Manifest auswählen. Unten ein Modell auswählen und den Download ausdrücklich starten. Vorhandene Texte und Codierungen bleiben nutzbar.',help);
const guide=el('a','Anleitung zur lokalen Modellinstallation',help);guide.href='/audio-model-setup';guide.target='_blank';guide.rel='noopener';
el('h3','Zentrale Modelle für alle Projekte',dialog);
const libraryPath=el('p','',dialog);libraryPath.id='audio-library-path';
const modelLabel=el('label','Modell zum Installieren',dialog),modelChoice=el('select',null,modelLabel);modelChoice.id='audio-download-model';
modelChoice.add(new Option('Whisper large-v3 (Standard)','large-v3'));modelChoice.add(new Option('Whisper small (kleiner)','small'));modelChoice.add(new Option('Sortformer v2 – Sprechererkennung bis 120 Minuten','sortformer-v2-onnx'));
el('p','Einmal herunterladen und zentral speichern. Dafür werden ausschließlich öffentliche Modelldateien von Hugging Face geladen, keine Projekt- oder Audiodaten gesendet. Bereits vollständig vorhandene zentrale Modelle werden geprüft und wiederverwendet.',dialog);
const download=el('button','Gewähltes Modell zentral herunterladen',dialog),copy=el('button','Gewählten vorhandenen Ordner zentral übernehmen',dialog),stop=el('button','Modellinstallation abbrechen',dialog);stop.hidden=true;
const installStatus=el('p','',dialog);installStatus.id='audio-install-status';installStatus.setAttribute('role','status');
let busy=false,parent=null,epoch=0,ownInstall=null,installRemember=false,libraryBusy=false,selectedInstall=null,refreshing=false;
const phase={checking:'Vorhandenes Modell prüfen',copying:'Vorhandene Modelldateien zentral kopieren',downloading:'Öffentliche Modelldateien herunterladen – dies kann einige Zeit dauern',verifying:'Modelldateien und Prüfsummen prüfen',completed:'Modell zentral verfügbar',cancelled:'Installation abgebrochen',failed:'Installation fehlgeschlagen'};
async function installation(state){const lib=state.library;if(!lib)return;libraryPath.textContent='Zentraler Modellordner: '+lib.root;libraryBusy=lib.busy;download.disabled=copy.disabled=lib.busy;apply.disabled=busy||lib.busy;stop.hidden=!lib.busy;const job=lib.job;installStatus.textContent=selectedInstall===job.id?'Modell zentral gespeichert und für dieses Projekt ausgewählt.':(job.status==='completed'&&job.model==='sortformer-v2-onnx'?'Sortformer v2 zentral bereit für die nächste Aufnahme.':phase[job.status]||'')+(job.error?' · '+job.error:'');if(ownInstall===job.id&&!lib.busy){ownInstall=null;if(job.status==='completed'){if(job.model==='sortformer-v2-onnx'){installStatus.textContent='Sortformer v2 zentral bereit. Wird bei der nächsten Aufnahme nach der Transkription automatisch verwendet; bestehende Ergebnisse bleiben unverändert.';return}try{const result=await api('/host-model-folder',{path:job.path,remember:installRemember});selectedInstall=job.id;path.value=result.path;summary.textContent='Bereit: '+result.path;installStatus.textContent='Modell zentral gespeichert und für dieses Projekt ausgewählt.'+(result.remembered?' Neue Projekte verwenden diese Auswahl ebenfalls.':'');window.dispatchEvent(new Event('audio-model-selected'));}catch(e){installStatus.textContent+=' · '+e.message}}}}
async function install(source){try{if(source&&!path.value.trim())throw Error('Zuerst den vorhandenen Modellordner auswählen.');installRemember=remember.checked;const job=await api('/host-model-install',{model:modelChoice.value,confirmed:true,source:source?path.value:null,remember:installRemember});ownInstall=job.id;await refresh()}catch(e){installStatus.textContent=e.message}}
download.onclick=()=>install(false);copy.onclick=()=>install(true);stop.onclick=async()=>{try{await api('/host-model-install-stop');installStatus.textContent='Abbruch angefordert; Prozessende wird abgewartet.'}catch(e){installStatus.textContent=e.message}};
async function refresh(){const state=await api('/host-model-state');summary.textContent=state.ready?'Bereit: '+state.path:'Einrichtung erforderlich: '+state.error;panel.dataset.ready=String(state.ready);const previous=known.value;known.replaceChildren(new Option('Modellordner auswählen …',''));for(const c of state.candidates)known.add(new Option(c.name+' — '+c.path,c.path));known.value=previous;await installation(state);return state}
window.openAudioModelSetup=async()=>{try{const state=await refresh();path.value=state.path;status.textContent=state.ready?'Die gespeicherte Auswahl bleibt bestehen, bis du eine neue bestätigst.':state.error;list.replaceChildren();up.disabled=true;if(!dialog.open)dialog.showModal()}catch(e){status.textContent=e.message;if(!dialog.open)dialog.showModal()}};
configure.onclick=window.openAudioModelSetup;
known.onchange=()=>{if(known.value){path.value=known.value;list.replaceChildren();++epoch;status.textContent='Mit „Modellordner prüfen und verwenden“ bestätigen.'}};
async function folders(value){const generation=++epoch;list.replaceChildren();status.textContent='Ordner wird geöffnet …';try{const result=await api('/host-model-browse',{path:value});if(generation!==epoch||!dialog.open)return;path.value=result.path;parent=result.parent;up.disabled=!parent;for(const d of result.directories){const b=el('button','📁 '+d.name,list);b.onclick=()=>folders(d.path)}status.textContent='Aktuellen Ordner mit „Modellordner prüfen und verwenden“ auswählen.'}catch(e){if(generation===epoch)status.textContent=e.message}}
browse.onclick=()=>folders(path.value);up.onclick=()=>folders(parent);home.onclick=()=>folders('');path.oninput=()=>{++epoch;list.replaceChildren()};
apply.onclick=async()=>{if(busy||libraryBusy)return;ownInstall=null;busy=true;apply.disabled=true;path.disabled=true;known.disabled=true;browse.disabled=true;home.disabled=true;up.disabled=true;status.textContent='Modelldateien und Prüfsummen werden geprüft …';try{const result=await api('/host-model-folder',{path:path.value,remember:remember.checked});await refresh();status.textContent='Modell bereit: '+result.model+(result.remembered?' · Für neue Projekte gespeichert.':' · Für dieses Projekt gespeichert.');window.dispatchEvent(new Event('audio-model-selected'));}catch(e){status.textContent=e.message}finally{busy=false;apply.disabled=false;path.disabled=false;known.disabled=false;browse.disabled=false;home.disabled=false;up.disabled=!parent}};
cancel.onclick=()=>{if(!busy)dialog.close()};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault()});dialog.addEventListener('close',()=>++epoch);
refresh().catch(e=>summary.textContent='Modelleinrichtung nicht erreichbar: '+e.message);
setInterval(()=>{if((dialog.open||libraryBusy)&&!refreshing){refreshing=true;refresh().catch(e=>installStatus.textContent=e.message).finally(()=>refreshing=false)}},2000);
})();
